<!DOCTYPE html>
<html lang="en">
<head>
    <?php
        include('component/head.html');
    ?>
</head>
<body>
    <?php
        include('component/header.html');
        include('component/banner.html');
        include('component/product-list.html');
        include('component/featured.html');
        include('component/sales.html');
        include('component/footer.html');
        include('component/contact-widget.html');
        include('component/marketplace.html');
        include('component/script.html');
    ?>

    <script>
        $('.owl-carousel').owlCarousel({
            loop:true,
            responsiveClass:true,
            autoplay:true,
            autoplayTimeout:2000,
            autoplayHoverPause:true,
            responsive:{
                0:{
                    items:2,
                    margin:25,
                    nav:true
                },
                600:{
                    items:3,
                    margin:10,
                    nav:false
                }
            }
        })
    </script>
</body>
</html>